### ISSUE TITLE
[Android] 配置例子

### ISSUE THREAD

**Issue by tyao1** [reactnativecn/react-native-talkingdata#1]
你好！ 我是安卓小白，请问

```
在你自定义的MainActivity的onCreate()中第一行加入
TalkingDataModule.register(getApplicationContext(), null, null, true);
```

有没有具体的例子可以参考，不知道onCreate要如何声明以及TalkingDataModule从哪里来，谢谢！

**Comment by quentinzhang** [comment]
同问，0.21版本的react native初始化项目之后，MainActivity里面似乎没有onCreate，加上TalkingDataModule.register(getApplicationContext(), null, null, true);一行之后一直报错：

> MainActivity.java:25: 错误: 找不到符号
> TalkingDataModule.register(getApplicationContext(), null, null, true);
>   符号:   变量 TalkingDataModule
>   位置: 类 MainActivity
> 1 个错误

**Comment by ipk2015** [comment]
呃，rnpm link这个命令执行的什么？rnpm不是设在本地的私有npm库吗？我觉得引入步骤应该少了几步，要不然没法注册到本地

**Comment by tdzl2003** [comment]
rnpm是react-native管理原生模块的辅助工具，和私有npm库没有任何关系。

onCreate没有的问题，我们稍后补充一下文档。

**Comment by ipk2015** [comment]
我之前没安装过rnpm,所以之前按步骤来注册不成功。
在rpm link执行之前应该执行下安装rnpm命令
`npm intall rnpm -g`
关于onCreate 的问题，直接重写下就可以
`@Override
    protected void onCreate(Bundle savedInstanceState) {
        TalkingDataModule.register(getApplicationContext(), null, null, true);
        super.onCreate(savedInstanceState);
    }`
虽然我最后集成成功了，不过还是遇到了个问题，appid在build.gradle里时会报错，不知道为啥，可能是gradle版本问题，不识别。后来我直接把app ID写死在集成模块的build.gradle里了，运行了后没有问题。

**Comment by tyao1** [comment]
刚发现这个issue是我发起的。之前搞定了就忘记了这个issue了，同楼上的解决方法。appid我这里貌似没问题 0 0

**Comment by sugar09** [comment]
TalkingDataModule 这个是怎么声明的？
